/* Generated by scripts/ingest-icons.mjs — do not edit by hand. */
import type { IconSetDef } from './types';
import { feather } from './feather';
import { lucide } from './lucide';
import { tabler } from './tabler';
import { heroicons } from './heroicons';
import { ph } from './ph';
import { ri } from './ri';
import { carbon } from './carbon';
import { ion } from './ion';
import { octicon } from './octicon';
import { mdi } from './mdi';
import { fa6Solid } from './fa6-solid';
import { bi } from './bi';
import { fluent } from './fluent';
import { materialSymbols } from './material-symbols';
import { simpleIcons } from './simple-icons';
import { fa6Brands } from './fa6-brands';

export type { IconSetDef };

/** Prefixes accepted in `<Icon name="prefix:glyph" />`. */
export type IconSetPrefix =
  | 'feather'
  | 'lucide'
  | 'tabler'
  | 'heroicons'
  | 'ph'
  | 'ri'
  | 'carbon'
  | 'ion'
  | 'octicon'
  | 'mdi'
  | 'fa6-solid'
  | 'bi'
  | 'fluent'
  | 'material-symbols'
  | 'simple-icons'
  | 'fa6-brands';

export const iconSets: Record<IconSetPrefix, IconSetDef> = {
  feather: feather,
  lucide: lucide,
  tabler: tabler,
  heroicons: heroicons,
  ph: ph,
  ri: ri,
  carbon: carbon,
  ion: ion,
  octicon: octicon,
  mdi: mdi,
  'fa6-solid': fa6Solid,
  bi: bi,
  fluent: fluent,
  'material-symbols': materialSymbols,
  'simple-icons': simpleIcons,
  'fa6-brands': fa6Brands,
};

export const iconSetNames = Object.keys(iconSets) as IconSetPrefix[];
